### ISSUE TITLE
Howto

### ISSUE THREAD

**Issue by antifa-ev** [kannes/kannes.github.io#1]
Hi Hannes,

how have you generated the XYZ tiles?

Grüße nach Hamburg

**Comment by kannes** [comment]
Moin moin!

Roughly https://www.datenatlas.de/geodata/public/working/usbuildingdata.blob.core.windows.net/usbuildings/script.sh to generate a fast, single GeoPackage. 

Then styled as black in QGIS and rendered with QTiles because that was the easiest (yet sloooow) way.

**Comment by antifa-ev** [comment]
Downloading was the easy part for me, but as I run a remote server I can't use QGIS. Do you know any other solution to generate tiles from a raw GeoJSON / GeoPackage?
