### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by antifa-ev** [kannes/kannes.github.io#2]
Könntest du bitte auf die neue Version 1.1 der Microsoft Buildings updaten?

**Comment by kannes** [comment]
Nee, sorry. Ich hab meine Neugierde mit der ersten Version befriedigt und weiß noch nicht, ob ich überhaupt neue GeoPackages for 1.1 bauen werde. Vielleicht irgendwann mal. Aber das Rendern war extrem nervig, das will ich nicht nochmal machen...
